### ISSUE TITLE
Plugin compatibility with GitLab Self-Hosting

### ISSUE THREAD

**Issue by clementfavre** [wilhelmer/mkdocs-multirepo#7]
Is it possible to implement accounting with GitLab using some kind of connection like with token?
In the same context, is it possible to link with private repos on Github?

**Comment by wilhelmer** [comment]
When running `mkdocs-multirepo --init`, the plugin simply calls `git submodule add <repo>` under the hood.

So if you want to use GitLab or private repos, simply call `git submodule add` with your custom options command instead of `mkdocs-multirepo --init`. 

Then, you can run `mkdocs-multirepo --update` and `--build` as usual.
